"""Project/Worker scaffolding plus systemd lifecycle handoff.

``do_new`` writes the on-disk layout a project needs; ``spawn_loop`` launches a
Worker's outer loop in a validated transient service and slice. Both are libraries the
``danus`` CLI verbs (``danus.orchestration``) call — kept here beside the loop +
layout so the file names, config template, and launch mechanism live in one place.

Notes:
  - Worker MCP wiring is injected as an absolute credential-free bridge to a
    per-round host-owned one-shot socket;
  - the config template + defaults (verify URL, model) come from env at CALL time
    (with a built-in fallback default), not hard-wired at import time.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional

from danus import codex
from danus.secure_io import atomic_write_text, ensure_private_dir, secure_open_text

from . import layout as L

# --------------------------------------------------------------------------- #
# atomic file helpers                                                         #
# --------------------------------------------------------------------------- #

def atomic_write(path: Path, text: str, *, mode: Optional[int] = None) -> None:
    """Write host state through a no-follow, random-temp atomic publish.

    ``0600`` is the default even for historically non-secret state.  Workers and
    Web orchestration run as the same service uid; group/world visibility is
    unnecessary and made predictable ``.tmp`` symlink attacks possible.
    """
    atomic_write_text(path, text, mode=0o600 if mode is None else mode)


def _toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symlink(target: Path, link: Path) -> None:
    """Best-effort symlink; degrade gracefully where symlinks are unsupported
    (the codex config still points at the repo, so the worker isn't broken)."""
    if link.is_symlink() or link.exists():
        return
    try:
        os.symlink(target, link)
    except OSError:
        pass


# --------------------------------------------------------------------------- #
# codex config template + task placeholder                                    #
# --------------------------------------------------------------------------- #

# Codex launches only a credential-free Unix-socket bridge.  The real gateway is
# a host-owned sidecar started by the trusted Worker loop, outside the provider
# sandbox; verifier URL/capability and Project identity never enter this file or
# the provider environment.  The high-precedence CLI wiring in
# ``execution.security`` repeats this configuration so a modified project file
# cannot weaken it between rounds.
_CODEX_CONFIG = """\
# Auto-generated by Danus; do not hand-edit.
# The Worker MCP endpoint is a per-round one-shot pathname socket, mounted only
# inside the provider service at a fixed private path.  High-precedence,
# fail-closed CLI configuration injects the credential-free bridge only after
# the host has pinned the provider cgroup; no reusable endpoint belongs here.
"""

_TASK_PLACEHOLDER = (
    "# Task\n\n(unassigned — the main agent writes your assignment here via "
    "`danus assign`; you read this file at the start of every round)\n"
)


def _default_model() -> str:
    return codex.model()


def write_codex_config(wl: "L.WorkerLayout") -> None:
    """Write the worker's ``.codex/config.toml``, pinning the gateway ``command``
    to THIS interpreter (``sys.executable``). Used at scaffold time and rewritten
    at every loop start (see ``loop.main``), so the worker's gateway always runs on
    the same Python as danus — never a bare ``python3`` that PATH could resolve to
    a different install (which would silently point the worker at another codebase
    / an incompatible ``mcp``)."""
    atomic_write(wl.codex_config, _CODEX_CONFIG, mode=0o600)


# --------------------------------------------------------------------------- #
# do_new — scaffold a project                                                 #
# --------------------------------------------------------------------------- #

def do_new(project: str, roles: str = "high:3,xhigh:4",
           model: Optional[str] = None, root: Optional[Path] = None,
           max_parallel_workers: Optional[int] = None) -> Dict:
    """Scaffold a project dir + one worker home per role. Refuses to clobber an
    existing project dir (no silent overwrite of a live fact graph). Returns
    ``{"project_dir", "workers"}``."""
    pdir = L.project_dir(project, root)
    if pdir.exists():
        raise SystemExit(f"project already exists: {pdir} (pick another name or remove it)")
    role_pairs = L.parse_roles(roles)
    model = model or _default_model()
    if max_parallel_workers is not None:
        max_parallel_workers = int(max_parallel_workers)
        if max_parallel_workers < 1:
            raise ValueError("max_parallel_workers must be >= 1")

    L.workers_dir(project, root).mkdir(parents=True, exist_ok=True)
    (pdir / "global_memory").mkdir(exist_ok=True)
    (pdir / "fact_graph").mkdir(exist_ok=True)

    created: List[str] = []
    for worker, base in role_pairs:
        wl = L.WorkerLayout(L.worker_dir(project, worker, root))
        ensure_private_dir(wl.local_memory)
        ensure_private_dir(wl.logs)
        ensure_private_dir(wl.dir / "workspace")

        # static contract + skills (symlinks stay in sync with the repo)
        symlink(L.worker_md(), wl.dir / "AGENTS.md")
        (wl.dir / ".agents").mkdir(exist_ok=True)
        symlink(L.worker_skills_dir(), wl.dir / ".agents" / "skills")

        # codex MCP wiring (role=worker)
        write_codex_config(wl)
        atomic_write(wl.task, _TASK_PLACEHOLDER)
        atomic_write(wl.role,
                     f"MODEL={model}\nREASONING_EFFORT={base}\nROLE={base}\nDANUS_AUTHOR={worker}\n")
        atomic_write(wl.status,
                     json.dumps({"worker": worker, "state": "created", "round": 0}, indent=2))
        created.append(worker)

    meta = {"name": project, "model": model, "roles": roles, "workers": created}
    if max_parallel_workers is not None:
        meta["max_parallel_workers"] = max_parallel_workers
    atomic_write(pdir / "project.json", json.dumps(meta, ensure_ascii=False, indent=2))
    return {"project_dir": str(pdir), "workers": created}


# --------------------------------------------------------------------------- #
# spawn_loop — systemd launch of one Worker's outer loop                      #
# --------------------------------------------------------------------------- #

def spawn_loop(wdir: Path):
    """Launch one managed Worker service/slice and return its exact handle.

    The caller retains the handle long enough to stop the exact newly created
    boundary if post-start identity verification fails.
    """
    wl = L.WorkerLayout(wdir)
    ensure_private_dir(wl.logs)
    from . import systemd_scope

    return systemd_scope.start_worker(wl)
